### ISSUE TITLE
role doesn't check that firewall service is actually running

### ISSUE THREAD

**Issue by dgibbs64** [robertdebock/ansible-role-firewall#16]
## Describe the bug

Role fails if ufw service is stopped.
Currently, this role doesn't check if the service is actually running and start it up if not.

To solve this I believe adding ansible.builtin.service task [here](https://github.com/robertdebock/ansible-role-firewall/blob/master/tasks/main.yml#L22) will resolve the issue.

**Comment by robertdebock** [comment]
Hi, thanks for the feedback.

In the end of the tasks-list, the firewall service is started:

```yaml
- name: start and enable firewall service
  ansible.builtin.service:
    name: "{{ firewall_service }}"
    state: started
    enabled: yes
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
    - firewall_service is defined
```

Is that sufficient, or do tasks fail when the service is not running? (In that case, the task that starts the service should be moved up.)
