### ISSUE TITLE
Allow adding a select interface to a selected zone.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-firewall#4]
## Proposed feature

I now need to manually run:
```
# firewall-cmd --zone=public --change-interface=enp0s25
```

**Comment by flybyray** [comment]
Currently the firewalld module is not able to manage this when NetworkManager manages the interface.

This is the issue which tracks that problem. https://github.com/ansible-collections/ansible.posix/issues/75

For now I use [a patched version](https://github.com/robertdebock/ansible-role-firewall/compare/5.1.4...ndgit:issue-4?expand=1) of this role.

As there are several usefull pull requests waiting. I personally use a custom merge branch. A useful `role-file.yml` could look like this:

```yaml
  - name: robertdebock.firewall
    scm: git
    src: https://github.com/<<your_fork>>/ansible-role-firewall.git
    version: 5.1.4-merge-branch
```

the patch has a provides a new flag `firewall_firewalld_nm_fix` which ensures some additional packages are installed ( i am not quiet sure if they are all needed just saw [Install needed network manager libs](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html) )

then a new list `firewall_interfaces` can hold interfaces and their zone.

```yaml
    - role: robertdebock.firewall
      firewall_firewalld_nm_fix: true
      firewall_interfaces:
        - interface: eth0
          zone: trusted
```
