### ISSUE TITLE
Add option to allow from specific source

### ISSUE THREAD

**Issue by rohankrishnadev** [robertdebock/ansible-role-firewall#5]
## Proposed feature

Add option for users to be able to configure source IP for a particular rule. 

## Rationale

As of now the firewall rules allow access from 0.0.0.0/0 but it would be useful to restrict the source to a certain IPs. For example, when I run a web server I'd like to allow access only from cloudflare IPs. 

## Additional context

If source IP isn't specified, then 0.0.0.0 can be used as default. Both firewall-cmd and ufw are able to support this.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by dgibbs64** [comment]
ufw example here

```
- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
```
