### ISSUE TITLE
The state of a servcie may be undefined in the iptables template

### ISSUE THREAD

**Issue by ashpool37** [robertdebock/ansible-role-firewall#8]
## Describe the bug
The comments in `defaults/main.yml` imply that the state of a service is assumed present if it's not specified. In `templates/iptables.j2` however this assumption is not taken into account, and the template will not compile if the state is not provided explicitly.

## Playbook
```yaml
---
- name: secure the host
  hosts: ***
  become: true
  gather_facts: true
  roles:
    - name: robertdebock.firewall
```

## Output
```
TASK [robertdebock.firewall : configure iptables] ******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'state'
fatal: [***]: FAILED! => {
    "changed": false
}

MSG:

AnsibleUndefinedVariable: 'dict object' has no attribute 'state'
```

## Environment

- Control node OS: Void Linux
- Control node Ansible version: 2.11.2
- Control node Jinja version: 2.11.3
- Managed node OS: Alpine 3.14.1
